# Generated by Django 5.2.6 on 2025-09-13 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car_DB',
            fields=[
                ('car_name', models.CharField(max_length=20)),
                ('chass_no', models.IntegerField(primary_key=True, serialize=False)),
                ('gear_box', models.CharField(max_length=20)),
                ('model_name', models.CharField(max_length=30)),
            ],
        ),
    ]
